# Generated by Django 4.2.5 on 2023-10-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
